<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://ws.test.ocean.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://ws.test.ocean.com" xmlns:intf="http://ws.test.ocean.com" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="testRequest">

   </wsdl:message>

   <wsdl:message name="testResponse">

   </wsdl:message>

   <wsdl:portType name="Aimp">

      <wsdl:operation name="test">

         <wsdl:input message="impl:testRequest" name="testRequest">

       </wsdl:input>

         <wsdl:output message="impl:testResponse" name="testResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="AimpSoapBinding" type="impl:Aimp">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="test">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="testRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.test.ocean.com" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="testResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.test.ocean.com" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="AimpService">

      <wsdl:port binding="impl:AimpSoapBinding" name="Aimp">

         <wsdlsoap:address location="http://tempuri.org/rpc-spring-hessian-client/services/Aimp"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
