
package cn.newcapec.function.platform.services;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SecretKeySoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SecretKeySoap {


    /**
     * Tac验证
     * 
     * @param verifyCode
     * @param makeCardID
     * @param verifyID
     * @param noteCase
     * @param tac
     * @param opFare
     * @param opdt
     * @param oddFare
     * @param opCount
     * @param poscode
     * @param asn
     * @param tacFalg
     * @param verifyServiceURL
     * @return
     *     returns cn.newcapec.function.platform.services.Result
     */
    @WebMethod(operationName = "CheckTAC", action = "http://tempuri.org/CheckTAC")
    @WebResult(name = "CheckTACResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckTAC", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.CheckTAC")
    @ResponseWrapper(localName = "CheckTACResponse", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.CheckTACResponse")
    public Result checkTAC(
        @WebParam(name = "VerifyServiceURL", targetNamespace = "http://tempuri.org/")
        String verifyServiceURL,
        @WebParam(name = "VerifyID", targetNamespace = "http://tempuri.org/")
        int verifyID,
        @WebParam(name = "VerifyCode", targetNamespace = "http://tempuri.org/")
        StringBuilder verifyCode,
        @WebParam(name = "ASN", targetNamespace = "http://tempuri.org/")
        BigInteger asn,
        @WebParam(name = "MakeCardID", targetNamespace = "http://tempuri.org/")
        long makeCardID,
        @WebParam(name = "NoteCase", targetNamespace = "http://tempuri.org/")
        int noteCase,
        @WebParam(name = "OddFare", targetNamespace = "http://tempuri.org/")
        int oddFare,
        @WebParam(name = "OpCount", targetNamespace = "http://tempuri.org/")
        int opCount,
        @WebParam(name = "OpFare", targetNamespace = "http://tempuri.org/")
        int opFare,
        @WebParam(name = "poscode", targetNamespace = "http://tempuri.org/")
        long poscode,
        @WebParam(name = "opdt", targetNamespace = "http://tempuri.org/")
        String opdt,
        @WebParam(name = "TAC", targetNamespace = "http://tempuri.org/")
        long tac,
        @WebParam(name = "tacFalg", targetNamespace = "http://tempuri.org/")
        int tacFalg);

    /**
     * 获取MAC码 
     * 
     * @param pMAC
     * @param verifyCode
     * @param verifyID
     * @param opDT
     * @param noteCase
     * @param posCode
     * @param opFare
     * @param oddFare
     * @param opCount
     * @param checkMACResult
     * @param asn
     * @param rand
     * @param verifyServiceURL
     */
    @WebMethod(operationName = "CheckMAC", action = "http://tempuri.org/CheckMAC")
    @RequestWrapper(localName = "CheckMAC", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.CheckMAC")
    @ResponseWrapper(localName = "CheckMACResponse", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.CheckMACResponse")
    public void checkMAC(
        @WebParam(name = "VerifyServiceURL", targetNamespace = "http://tempuri.org/")
        String verifyServiceURL,
        @WebParam(name = "VerifyID", targetNamespace = "http://tempuri.org/")
        int verifyID,
        @WebParam(name = "VerifyCode", targetNamespace = "http://tempuri.org/")
        StringBuilder verifyCode,
        @WebParam(name = "ASN", targetNamespace = "http://tempuri.org/")
        BigInteger asn,
        @WebParam(name = "Rand", targetNamespace = "http://tempuri.org/")
        long rand,
        @WebParam(name = "NoteCase", targetNamespace = "http://tempuri.org/")
        int noteCase,
        @WebParam(name = "OddFare", targetNamespace = "http://tempuri.org/")
        int oddFare,
        @WebParam(name = "OpCount", targetNamespace = "http://tempuri.org/")
        int opCount,
        @WebParam(name = "OpFare", targetNamespace = "http://tempuri.org/")
        int opFare,
        @WebParam(name = "posCode", targetNamespace = "http://tempuri.org/")
        BigInteger posCode,
        @WebParam(name = "OpDT", targetNamespace = "http://tempuri.org/")
        StringBuilder opDT,
        @WebParam(name = "pMAC", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<Long> pMAC,
        @WebParam(name = "CheckMACResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Result> checkMACResult);

    /**
     * 获取发卡密钥
     * 
     * @param verifyCode
     * @param verifyID
     * @param encKey
     * @param purseSector
     * @param totolSec
     * @param cardsnr
     * @param verifyServiceURL
     * @param getKeyForPublishResult
     * @param cardMac
     */
    @WebMethod(operationName = "GetKeyForPublish", action = "http://tempuri.org/GetKeyForPublish")
    @RequestWrapper(localName = "GetKeyForPublish", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.GetKeyForPublish")
    @ResponseWrapper(localName = "GetKeyForPublishResponse", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.GetKeyForPublishResponse")
    public void getKeyForPublish(
        @WebParam(name = "VerifyServiceURL", targetNamespace = "http://tempuri.org/")
        String verifyServiceURL,
        @WebParam(name = "VerifyID", targetNamespace = "http://tempuri.org/")
        int verifyID,
        @WebParam(name = "VerifyCode", targetNamespace = "http://tempuri.org/")
        StringBuilder verifyCode,
        @WebParam(name = "totolSec", targetNamespace = "http://tempuri.org/")
        int totolSec,
        @WebParam(name = "purseSector", targetNamespace = "http://tempuri.org/")
        int purseSector,
        @WebParam(name = "cardsnr", targetNamespace = "http://tempuri.org/")
        StringBuilder cardsnr,
        @WebParam(name = "cardMac", targetNamespace = "http://tempuri.org/")
        StringBuilder cardMac,
        @WebParam(name = "encKey", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<String> encKey,
        @WebParam(name = "GetKeyForPublishResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Result> getKeyForPublishResult);

    /**
     * 获取消费密钥
     * 
     * @param sectorInfo
     * @param verifyCode
     * @param verifyID
     * @param encKey
     * @param cardsnr
     * @param verifyServiceURL
     * @param getKeyForAppResult
     * @param cardMac
     */
    @WebMethod(operationName = "GetKeyForApp", action = "http://tempuri.org/GetKeyForApp")
    @RequestWrapper(localName = "GetKeyForApp", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.GetKeyForApp")
    @ResponseWrapper(localName = "GetKeyForAppResponse", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.GetKeyForAppResponse")
    public void getKeyForApp(
        @WebParam(name = "VerifyServiceURL", targetNamespace = "http://tempuri.org/")
        String verifyServiceURL,
        @WebParam(name = "VerifyID", targetNamespace = "http://tempuri.org/")
        int verifyID,
        @WebParam(name = "VerifyCode", targetNamespace = "http://tempuri.org/")
        StringBuilder verifyCode,
        @WebParam(name = "sectorInfo", targetNamespace = "http://tempuri.org/")
        StringBuilder sectorInfo,
        @WebParam(name = "cardsnr", targetNamespace = "http://tempuri.org/")
        StringBuilder cardsnr,
        @WebParam(name = "cardMac", targetNamespace = "http://tempuri.org/")
        StringBuilder cardMac,
        @WebParam(name = "encKey", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<String> encKey,
        @WebParam(name = "GetKeyForAppResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Result> getKeyForAppResult);

    /**
     * 获得充值密钥
     * 
     * @param verifyCode
     * @param verifyID
     * @param getTopUpKeyResult
     * @param sCardSnr
     * @param verifyServiceURL
     * @param key
     * @param cardMac
     */
    @WebMethod(operationName = "GetTopUpKey", action = "http://tempuri.org/GetTopUpKey")
    @RequestWrapper(localName = "GetTopUpKey", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.GetTopUpKey")
    @ResponseWrapper(localName = "GetTopUpKeyResponse", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.GetTopUpKeyResponse")
    public void getTopUpKey(
        @WebParam(name = "VerifyServiceURL", targetNamespace = "http://tempuri.org/")
        String verifyServiceURL,
        @WebParam(name = "VerifyID", targetNamespace = "http://tempuri.org/")
        int verifyID,
        @WebParam(name = "VerifyCode", targetNamespace = "http://tempuri.org/")
        StringBuilder verifyCode,
        @WebParam(name = "sCardSnr", targetNamespace = "http://tempuri.org/")
        String sCardSnr,
        @WebParam(name = "cardMac", targetNamespace = "http://tempuri.org/")
        String cardMac,
        @WebParam(name = "key", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<String> key,
        @WebParam(name = "GetTopUpKeyResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Result> getTopUpKeyResult);

    /**
     * 获取充值密钥，制卡中心发卡前中间密钥
     * 
     * @param citycode
     * @param verifyCode
     * @param verifyID
     * @param encKey
     * @param getKeyForGJMidKeyResult
     * @param verifyServiceURL
     */
    @WebMethod(operationName = "GetKeyForGJMidKey", action = "http://tempuri.org/GetKeyForGJMidKey")
    @RequestWrapper(localName = "GetKeyForGJMidKey", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.GetKeyForGJMidKey")
    @ResponseWrapper(localName = "GetKeyForGJMidKeyResponse", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.GetKeyForGJMidKeyResponse")
    public void getKeyForGJMidKey(
        @WebParam(name = "VerifyServiceURL", targetNamespace = "http://tempuri.org/")
        String verifyServiceURL,
        @WebParam(name = "VerifyID", targetNamespace = "http://tempuri.org/")
        int verifyID,
        @WebParam(name = "VerifyCode", targetNamespace = "http://tempuri.org/")
        StringBuilder verifyCode,
        @WebParam(name = "citycode", targetNamespace = "http://tempuri.org/")
        StringBuilder citycode,
        @WebParam(name = "encKey", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<String> encKey,
        @WebParam(name = "GetKeyForGJMidKeyResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Result> getKeyForGJMidKeyResult);

    /**
     * 注册PSAM卡
     * 
     * @param printCode
     * @param endDT
     * @param verifyCode
     * @param verifyID
     * @param sCardSNR
     * @param beginDT
     * @param psamCode
     * @param posCode
     * @param verifyServiceURL
     * @return
     *     returns cn.newcapec.function.platform.services.Result
     */
    @WebMethod(operationName = "PsamCardRegister", action = "http://tempuri.org/PsamCardRegister")
    @WebResult(name = "PsamCardRegisterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PsamCardRegister", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.PsamCardRegister")
    @ResponseWrapper(localName = "PsamCardRegisterResponse", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.PsamCardRegisterResponse")
    public Result psamCardRegister(
        @WebParam(name = "VerifyServiceURL", targetNamespace = "http://tempuri.org/")
        String verifyServiceURL,
        @WebParam(name = "VerifyID", targetNamespace = "http://tempuri.org/")
        int verifyID,
        @WebParam(name = "VerifyCode", targetNamespace = "http://tempuri.org/")
        StringBuilder verifyCode,
        @WebParam(name = "PsamCode", targetNamespace = "http://tempuri.org/")
        String psamCode,
        @WebParam(name = "PrintCode", targetNamespace = "http://tempuri.org/")
        String printCode,
        @WebParam(name = "sCardSNR", targetNamespace = "http://tempuri.org/")
        String sCardSNR,
        @WebParam(name = "PosCode", targetNamespace = "http://tempuri.org/")
        BigInteger posCode,
        @WebParam(name = "BeginDT", targetNamespace = "http://tempuri.org/")
        String beginDT,
        @WebParam(name = "EndDT", targetNamespace = "http://tempuri.org/")
        String endDT);

    /**
     * 操作PSAM卡
     * 
     * @param opReason
     * @param verifyCode
     * @param verifyID
     * @param opType
     * @param posCode
     * @param verifyServiceURL
     * @return
     *     returns cn.newcapec.function.platform.services.Result
     */
    @WebMethod(operationName = "PsamCardStatusMng", action = "http://tempuri.org/PsamCardStatusMng")
    @WebResult(name = "PsamCardStatusMngResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PsamCardStatusMng", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.PsamCardStatusMng")
    @ResponseWrapper(localName = "PsamCardStatusMngResponse", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.PsamCardStatusMngResponse")
    public Result psamCardStatusMng(
        @WebParam(name = "VerifyServiceURL", targetNamespace = "http://tempuri.org/")
        String verifyServiceURL,
        @WebParam(name = "VerifyID", targetNamespace = "http://tempuri.org/")
        int verifyID,
        @WebParam(name = "VerifyCode", targetNamespace = "http://tempuri.org/")
        StringBuilder verifyCode,
        @WebParam(name = "OpType", targetNamespace = "http://tempuri.org/")
        int opType,
        @WebParam(name = "PosCode", targetNamespace = "http://tempuri.org/")
        BigInteger posCode,
        @WebParam(name = "OpReason", targetNamespace = "http://tempuri.org/")
        String opReason);

    /**
     * 获取充值密钥，制卡中心发卡前中间密钥
     * 
     * @param strDataIn
     * @param verifyCode
     * @param verifyID
     * @param strDataOut
     * @param verifyServiceURL
     * @return
     *     returns cn.newcapec.function.platform.services.Result
     */
    @WebMethod(operationName = "NFC_CommonInterFace", action = "http://tempuri.org/NFC_CommonInterFace")
    @WebResult(name = "NFC_CommonInterFaceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NFC_CommonInterFace", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.NFCCommonInterFace")
    @ResponseWrapper(localName = "NFC_CommonInterFaceResponse", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.NFCCommonInterFaceResponse")
    public Result nfcCommonInterFace(
        @WebParam(name = "VerifyServiceURL", targetNamespace = "http://tempuri.org/")
        String verifyServiceURL,
        @WebParam(name = "VerifyID", targetNamespace = "http://tempuri.org/")
        int verifyID,
        @WebParam(name = "VerifyCode", targetNamespace = "http://tempuri.org/")
        StringBuilder verifyCode,
        @WebParam(name = "strDataIn", targetNamespace = "http://tempuri.org/")
        String strDataIn,
        @WebParam(name = "strDataOut", targetNamespace = "http://tempuri.org/")
        StringBuilder strDataOut);

    /**
     * 关闭与UKey的会话事务
     * 
     * @param sessionID
     * @return
     *     returns cn.newcapec.function.platform.services.Result
     */
    @WebMethod(operationName = "CloseKeySession", action = "http://tempuri.org/CloseKeySession")
    @WebResult(name = "CloseKeySessionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CloseKeySession", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.CloseKeySession")
    @ResponseWrapper(localName = "CloseKeySessionResponse", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.CloseKeySessionResponse")
    public Result closeKeySession(
        @WebParam(name = "sessionID", targetNamespace = "http://tempuri.org/")
        String sessionID);

    /**
     * 打开key的session
     * 
     * @param sessionID
     * @param keyUser
     * @param reserved
     * @param sysCode
     * @param keyUserPwd
     * @return
     *     returns cn.newcapec.function.platform.services.Result
     */
    @WebMethod(operationName = "CreateKeySession", action = "http://tempuri.org/CreateKeySession")
    @WebResult(name = "CreateKeySessionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateKeySession", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.CreateKeySession")
    @ResponseWrapper(localName = "CreateKeySessionResponse", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.CreateKeySessionResponse")
    public Result createKeySession(
        @WebParam(name = "sysCode", targetNamespace = "http://tempuri.org/")
        String sysCode,
        @WebParam(name = "keyUser", targetNamespace = "http://tempuri.org/")
        String keyUser,
        @WebParam(name = "keyUserPwd", targetNamespace = "http://tempuri.org/")
        String keyUserPwd,
        @WebParam(name = "sessionID", targetNamespace = "http://tempuri.org/")
        StringBuilder sessionID,
        @WebParam(name = "reserved", targetNamespace = "http://tempuri.org/")
        StringBuilder reserved);

    /**
     * 取出本机的特征码
     * 
     * @param getSerialNOResult
     * @param sysCode
     */
    @WebMethod(operationName = "GetSerialNO", action = "http://tempuri.org/GetSerialNO")
    @RequestWrapper(localName = "GetSerialNO", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.GetSerialNO")
    @ResponseWrapper(localName = "GetSerialNOResponse", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.GetSerialNOResponse")
    public void getSerialNO(
        @WebParam(name = "sysCode", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<String> sysCode,
        @WebParam(name = "GetSerialNOResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Result> getSerialNOResult);

    /**
     * 解析公司发回的授权码,返回从授权码中解析出来的Key用户名和密码
     * 
     * @param grantCode
     * @param phaseCodeStrResult
     * @param newKeyPwd
     * @param keyOPCmd
     * @param keyUser
     * @param oldKeyPwd
     * @param sysCode
     */
    @WebMethod(operationName = "PhaseCodeStr", action = "http://tempuri.org/PhaseCodeStr")
    @RequestWrapper(localName = "PhaseCodeStr", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.PhaseCodeStr")
    @ResponseWrapper(localName = "PhaseCodeStrResponse", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.PhaseCodeStrResponse")
    public void phaseCodeStr(
        @WebParam(name = "sysCode", targetNamespace = "http://tempuri.org/")
        String sysCode,
        @WebParam(name = "grantCode", targetNamespace = "http://tempuri.org/")
        String grantCode,
        @WebParam(name = "keyOPCmd", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<Integer> keyOPCmd,
        @WebParam(name = "keyUser", targetNamespace = "http://tempuri.org/")
        StringBuilder keyUser,
        @WebParam(name = "oldKeyPwd", targetNamespace = "http://tempuri.org/")
        StringBuilder oldKeyPwd,
        @WebParam(name = "newKeyPwd", targetNamespace = "http://tempuri.org/")
        StringBuilder newKeyPwd,
        @WebParam(name = "PhaseCodeStrResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Result> phaseCodeStrResult);

    /**
     * 从Key中提取系统参数信息
     * 
     * @param sessionID
     * @param retrieveSysInfoResult
     * @param customerInfo
     */
    @WebMethod(operationName = "RetrieveSysInfo", action = "http://tempuri.org/RetrieveSysInfo")
    @RequestWrapper(localName = "RetrieveSysInfo", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.RetrieveSysInfo")
    @ResponseWrapper(localName = "RetrieveSysInfoResponse", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.RetrieveSysInfoResponse")
    public void retrieveSysInfo(
        @WebParam(name = "sessionID", targetNamespace = "http://tempuri.org/")
        String sessionID,
        @WebParam(name = "customerInfo", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<AppCustomerInfo> customerInfo,
        @WebParam(name = "RetrieveSysInfoResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Result> retrieveSysInfoResult);

    /**
     * 调用程序与UKEY在会话打开期间进行握手验证,看否UKEY还正常存在
     * 
     * @param response
     * @param sessionID
     * @return
     *     returns cn.newcapec.function.platform.services.Result
     */
    @WebMethod(operationName = "ValidKeyProp", action = "http://tempuri.org/ValidKeyProp")
    @WebResult(name = "ValidKeyPropResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidKeyProp", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.ValidKeyProp")
    @ResponseWrapper(localName = "ValidKeyPropResponse", targetNamespace = "http://tempuri.org/", className = "cn.newcapec.function.platform.services.ValidKeyPropResponse")
    public Result validKeyProp(
        @WebParam(name = "sessionID", targetNamespace = "http://tempuri.org/")
        String sessionID,
        @WebParam(name = "response", targetNamespace = "http://tempuri.org/")
        StringBuilder response);

}
